name: Deploy

on:
  push:
    branches:
      - main
     

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código, para ter acesso aos arquivos do nosso repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Instala o pnpm (Necessário para rodar pnpm run)
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      # 3. Configura o Node.js v20 (Compatível com React 19)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # 4. Instala as dependências listadas no package.json (Equivalente ao npm ci)
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 5. Executa os scripts criados
      - name: Run ESLint
        run: pnpm run eslint:check

      - name: Run Prettier
        run: pnpm run prettier:check
      
      - name: Run Test
        run: pnpm run test

  deploy:
    # Garante que o deploy só rode se o job 'check' (testes/lint) passar
    needs: check
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy to Production (Render)
        run: curl -f "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"

