# Arquivo que define uma github action
name: Deploy

on:
  push:
    branches:
    - main
    - develop

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      # Da acesso ao c√≥digo (Action GitHub)
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ESLint
        uses: pnpm run eslint:check

      - name: Prettier
        uses: pnpm run prettier:check
      
      - name: Test
        uses: pnpm run test